//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crudoptwithsearchdata.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class states2
    {
        public states2()
        {
            this.Employes = new HashSet<Employe>();
        }
    
        public int StateId { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Employe> Employes { get; set; }
    }
}
